language: node_js

node_js:
  - "20"

before_install:
  - npm config set progress false

jobs:
  include:
    - stage: lint_test
      name: "Linting Frontend"
      script:
        - cd client
        - yarn install
        - yarn pretest

    - name: "Linting & Formatting Backend"
      script:
        - yarn format

    - name: "Testing Backend"
      script:
        - yarn test
